version: "3.9" 
services:
  mongodb:
      image: mongo
      restart: always
      ports:
        - 27017:27017
  rbh-interview-system:
      build: .
      ports:
          - 8080:8080
      environment:
          MONGO_URI: mongodb://mongodb:27017
    